"use client";
// TODO: convert it to a server component

import './globals.css'
import { Inter } from 'next/font/google'
import TopNavBar from './components/TopNavBar'
import Footer from './components/Footer'
import Provider from './components/Provider'
import { CssBaseline, NextUIProvider } from "@nextui-org/react"

const inter = Inter({ subsets: ["latin"] })

// Commented out below code because 'use client' doesn't like it
// export const metadata = {
//   title: "mosPic",
//   description: "Generated by create next app",
// };

export default function RootLayout({
  children,
}) {
  return (
    <html lang="en">
      <Provider>
        <head>
          {CssBaseline.flush()}

          {/* <!-- onnxruntime-web --> */}
          <script src="https://cdn.jsdelivr.net/npm/onnxruntime-web/dist/ort.min.js"></script>
          {/* <!-- opencv --> */}
          <script src="https://docs.opencv.org/3.4/opencv.js"></script>
          <script src="/client/script/init.js" type="module"></script>
          <script src="/client/script/numpy.js"></script>
        </head>

        <body className={inter.className}>
          <div className='flex flex-col relative min-h-screen'>
            <div className='fixed top-0 left-0 right-0'>
              <TopNavBar />
            </div>

            <NextUIProvider>
              <div className='mt-16 mb-48'>
                { children }
              </div>
            </NextUIProvider>

            <div className='absolute bottom-0 left-0 right-0'>
              <Footer/>
            </div>
          </div>
        </body>
      </Provider>
    </html>
  );
}
