'use client';

import '../globals.css'
import { Inter } from 'next/font/google'
import UserTopNavbar from "./components/UserTopNavbar";
import UserSidebar from "./components/UserSidebar";

const inter = Inter({ subsets: ['latin'] })

export const metadata = {
  title: 'mosPic',
  description: 'Generated by create next app',
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="en">
        <div className="grid min-h-screen grid-rows-header">
            <UserTopNavbar />
            <div className="grid md:grid-cols-sidebar">
                <UserSidebar />
                <div className="grid md:grid-col-2 bg-gray-100">
                    <div >{children}</div>
                </div>
            </div>
        </div>
    </html>
  );
}