"use client";

import "../globals.css";
import { Inter } from "next/font/google";
import UserTopNavbar from "./components/UserTopNavbar";
import UserSidebar from "./components/UserSidebar";

const inter = Inter({ subsets: ["latin"] });

export const metadata = {
  title: "mosPic",
  description: "Generated by create next app",
};

export default function UserLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <div className={inter.className}>
      <div className="grid md:grid-rows-header">
        <UserTopNavbar />
        <div className="grid md:grid-cols-sidebar">
          <UserSidebar />
          <div className="bg-stone-50 top-[64px]">{children}</div>
        </div>
      </div>
    </div>
  );
}
